# Generated by Django 5.0.2 on 2024-07-24 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_user_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_no',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rating',
        ),
    ]
