# Generated by Django 5.0.2 on 2024-05-21 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('plot_no', models.IntegerField()),
                ('no_of_floor', models.IntegerField()),
                ('toatal_basement', models.IntegerField()),
                ('toatal_area', models.IntegerField()),
                ('vacant_area', models.IntegerField()),
                ('per_floor_area', models.IntegerField()),
                ('type', models.CharField(choices=[('Commercial', 'Commercial'), ('Residential', 'Residential'), ('Industrial', 'Industrial'), ('Agricultural', 'Agricultural'), ('Other', 'Other')], max_length=100)),
                ('power_backup', models.BooleanField()),
                ('air_conditioned', models.BooleanField()),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zone', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='properties/')),
                ('status', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('features', models.ManyToManyField(to='properties.features')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('cam_charges', models.IntegerField()),
                ('vacating_area', models.IntegerField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.properties')),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_no', models.IntegerField()),
                ('unit_available', models.IntegerField()),
                ('total_unit', models.IntegerField()),
                ('floor_area', models.IntegerField()),
                ('floor_plan', models.ImageField(upload_to='floor/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.properties')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_no', models.IntegerField()),
                ('area', models.IntegerField()),
                ('price', models.IntegerField()),
                ('no_of_parking', models.IntegerField()),
                ('available_for', models.CharField(max_length=100)),
                ('furnishng_status', models.CharField(max_length=100)),
                ('age_of_furnishing', models.IntegerField()),
                ('photo', models.ImageField(upload_to='unit/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.properties')),
            ],
        ),
    ]
