# Generated by Django 5.0.2 on 2024-05-22 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_remove_properties_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='plot_no',
            field=models.CharField(max_length=20),
        ),
    ]
