# Generated by Django 5.0.2 on 2024-05-24 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_remove_unit_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.unit'),
        ),
        migrations.AddField(
            model_name='unit',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.floor'),
        ),
    ]
