# Generated by Django 5.0.2 on 2024-05-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_owner_unit_unit_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='air_conditioned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='properties',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='per_floor_area',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='properties/'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='plot_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='power_backup',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='properties',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='properties',
            name='toatal_area',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='toatal_basement',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='vacant_area',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='zone',
            field=models.CharField(default='North', max_length=100),
        ),
    ]
