# Generated by Django 5.0.2 on 2024-07-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_properties_air_conditioned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='floor_plan',
            field=models.ImageField(blank=True, null=True, upload_to='floor/'),
        ),
    ]
