# Generated by Django 5.0.2 on 2024-07-28 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_properties_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='spoc',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='owner',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='properties.unit'),
        ),
    ]
