# Generated by Django 5.0.2 on 2024-08-30 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_alter_properties_no_of_floor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='cam_charges',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='vacating_area',
        ),
        migrations.AlterField(
            model_name='properties',
            name='type',
            field=models.CharField(choices=[('Commercial', 'Commercial'), ('Residential', 'Residential'), ('Industrial', 'Industrial'), ('Agricultural', 'Agricultural'), ('IT/ITES', 'IT/ITES'), ('Institutional', 'Institutional'), ('Hotel/Hospital', 'Hotel/Hospital'), ('Warehouse', 'Warehouse'), ('Land', 'Land'), ('Other', 'Other')], max_length=100),
        ),
    ]
