# Generated by Django 5.0.2 on 2024-10-21 23:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_rename_zone_properties_sub_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='ownership_type',
            field=models.CharField(blank=True, choices=[('Owner', 'Owner'), ('Tenant', 'Tenant'), ('Broker', 'Broker')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='properties',
            name='maintenance_charges',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='date_avability',
            field=models.DateField(default='2021-01-01'),
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_photo',
            field=models.FileField(blank=True, null=True, upload_to='unit/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'dwg', 'jpg', 'dxf'])]),
        ),
        migrations.AlterField(
            model_name='floor',
            name='floor_plan',
            field=models.FileField(blank=True, null=True, upload_to='floor/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'dwg', 'jpg', 'dxf'])]),
        ),
        migrations.AlterField(
            model_name='properties',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='properties/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'dwg', 'jpg', 'dxf'])]),
        ),
    ]
